Fix typo for wagtailsnippets JS
Currently, it's not possible to select a snippet because the JS file is not loaded, resulting in the error:
ReferenceError: createSnippetChooser is not defined

This is due to a typo in the gulp config file.